#spring:
#  application:
#    name: service-product
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#      config:
#        import-check:
#          enabled: false
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#      eager: true
#server:
#  port: 8000